### ISSUE TITLE
Octoprint API Secrets

### ISSUE THREAD

**Issue by brianjking** [samabsalom/Home-Assistant-Config#1]
https://github.com/samabsalom/Home-Assistant-Config/blob/packages/packages/octoprint.yaml#L3

Hey @samabsalom -- Was just checking out your Home Assistant config files and saw you've got your OctoPrint API key publicly available instead of in your `secrets.yaml`. Might want to fix that 👍!

**Comment by samabsalom** [comment]
Thank you !
